### ISSUE TITLE
Git: not found error

### ISSUE THREAD

**Issue by greenafrican** [net-engine/github-repository-sync-action#4]
Issue using this in a GitHub action:

```
/entrypoint.sh: line 8: git: not found
/entrypoint.sh: line 9: git: not found
```

Yaml is:
```
name: CI
on:
  push:
    branches: [main]
jobs:
  codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: net-engine/github-repository-sync-action@v1
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: ${{ secrets.CODECOMMIT_URL }}
```
